package ai.omnivoice.poc

import org.json.JSONObject
import java.io.File

/**
 * Fixtures are generated by `scripts/make_fixtures.py` from the Python
 * reference. They are read from android/fixtures/ via the test resource path
 * configured in app/build.gradle.kts, so regenerating them immediately
 * re-tests the Kotlin ports.
 */
object Fixtures {
    private val ROOT: File = run {
        var d = File(System.getProperty("user.dir")!!)
        while (!File(d, "android/fixtures").isDirectory && d.parentFile != null) d = d.parentFile!!
        d
    }

    fun repoFile(rel: String) = File(ROOT, rel)

    fun load(name: String): JSONObject =
        JSONObject(File(ROOT, "android/fixtures/$name").readText())

    val tokenizerJson: String by lazy {
        val local = File(ROOT, "models/omnivoice/tokenizer.json")
        check(local.isFile) {
            "models/omnivoice/tokenizer.json is missing — run scripts/download_models.py"
        }
        local.readText()
    }
}
