plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
}

android {
    namespace = "ai.omnivoice.poc"
    compileSdk = 36

    defaultConfig {
        applicationId = "ai.omnivoice.poc"
        minSdk = 31
        targetSdk = 36
        versionCode = 1
        versionName = "0.1-poc"
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        // the backbone is int4 ARM64 kernels; there is no reason to ship anything else
        ndk { abiFilters += listOf("arm64-v8a") }
    }

    buildTypes {
        release {
            isMinifyEnabled = false
        }
        debug {
            isMinifyEnabled = false
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }

    sourceSets {
        getByName("main") { kotlin.srcDirs("src/main/kotlin") }
        getByName("androidTest") { kotlin.srcDirs("src/androidTest/kotlin") }
        getByName("test") {
            kotlin.srcDirs("src/test/kotlin")
            // fixtures generated by scripts/make_fixtures.py — the JVM tests read
            // them straight from the repo instead of duplicating them into assets
            resources.srcDirs("../fixtures")
        }
    }

    testOptions {
        unitTests.isReturnDefaultValues = true
        unitTests.all { it.useJUnitPlatform() }
    }

    packaging {
        // ORT ships prebuilt .so; do not let the packer touch them
        jniLibs { useLegacyPackaging = false }
    }
}

dependencies {
    implementation("androidx.core:core-ktx:1.13.1")
    implementation("androidx.appcompat:appcompat:1.7.0")
    implementation("androidx.activity:activity-ktx:1.9.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    // Full build: com.microsoft contrib ops (MatMulNBits, GatherBlockQuantized)
    // plus the NNAPI and XNNPACK providers. Verified on desktop 1.22.0 that both
    // shipping graphs load — docs/benchmark.md §6.
    //
    // The `-qnn` variant was tried and reverted: its bundled QNN SDK cannot
    // create a device on this SoC (docs/benchmark.md §7.7). It costs +122 MB of
    // APK for HTP skels that stop at V79 while this chip is V81. To retry once
    // ORT ships a newer QNN SDK, swap the line below for
    // `onnxruntime-android-qnn` and run with `-e backend QNN`; the Backend.QNN
    // code path is kept for exactly that.
    implementation("com.microsoft.onnxruntime:onnxruntime-android:1.22.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testImplementation("org.json:json:20240303")

    // on-device benchmark harness: JUnit4, because that is what AndroidJUnitRunner drives
    androidTestImplementation("androidx.test.ext:junit:1.2.1")
    androidTestImplementation("androidx.test:runner:1.6.2")
    androidTestImplementation("androidx.test:rules:1.6.1")
}
